# Generated by Django 3.2.19 on 2024-01-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20240103_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='moviesID',
            new_name='movieID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
