# Generated by Django 3.2.19 on 2024-01-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20240103_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genraID',
            new_name='genreID',
        ),
    ]
