# Generated by Django 3.2.19 on 2024-01-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20240105_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genreID',
            field=models.ForeignKey(db_column='genreID', on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='App.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releaseDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
